apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webserver
    spec:
      containers:
          - name: webserver
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret
                readOnly: true
            ports:
              - containerPort: 80
            command: ["sh", "-c", "while true; do cat /etc/secret/{{ .Values.secretKey }} > /usr/share/nginx/html/index.html; sleep 5; done && nginx -g 'daemon off;'"]
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.secretName }}