apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/secret_printer_webserver"
type: Opaque
stringData:
  password: <password>
  user: <user>