apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/demo"
type: Opaque
stringData:
  password: <path:kv-v2/data/demo#password>
  user: <path:kv-v2/data/demo#user>