apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rbr-coder/vault_in_gitops'  # Replace with your actual repository URL
    targetRevision: HEAD  # You can specify a branch, tag, or commit hash
    path: secret_printer_webserver  # The path where the Helm chart or manifests for the webserver are stored
    plugin: {}
    helm:
      valueFiles: # Optional: Pfad zur values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webserver  # The namespace where the webserver will be deployed
  syncPolicy:
    automated:
      prune: true  # Automatically remove resources that are no longer present in Git
      selfHeal: true  # Automatically sync if something changes out of band
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
