kind: Secret
apiVersion: v1
metadata:
  name: vault-config
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: {{ .Values.vault.k8sRole }}
  AVP_TYPE: "vault"
  VAULT_ADDR: {{ .Values.vault.address }}