apiVersion: v1
data:
  VAULT_ADDR: aHR0cDovL3ZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  VAULT_TOKEN: aHZzLkt4U0ppTUZaUzJjbWF0RWtjbEZNZEs2ZQ==
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: dG9rZW4=
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque