apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rbr-coder/vault_in_gitops'  # Replace with your actual repository URL
    targetRevision: main  # You can specify a branch, tag, or commit hash
    path: secret_printer_webserver  # The path where the Helm chart or manifests for the webserver are stored
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: webserver  # The namespace where the webserver will be deployed
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
